---
- name: "Generating Inventory Of Key To Be Rotated"
  hosts: localhost
  vars_files:
    - key.vars  
  tasks:
    
    # ---------------------------------------------------------------
    # Getting Information About Of Ec2's Which Need key To be Rotated
    # ---------------------------------------------------------------
    
    - name: "Fetching Detail About Ec2 Instance"
      ec2_instance_info:
        aws_access_key: "{{ access_key }}"
        aws_secret_key: "{{ secret_key }}"
        region: "ap-south-1"
        filters:
          "key-name": "{{ old_key }}"
          instance-state-name: [ "running"]
      register: ec2
    
    
    # ------------------------------------------------------------
    # Creating Inventory Of Ec2  With Old Ssh-keyPair
    # ------------------------------------------------------------    
    - name: "Creating Inventory "
      add_host:
        name: "{{ item.public_ip_address }}"
        groups: "aws"
        ansible_host: "{{ item.public_ip_address }}"
        ansible_port: 22
        ansible_user: "ec2-user"
        ansible_ssh_private_key_file: "{{ old_key }}.pem"
        ansible_ssh_common_args: "-o StrictHostKeyChecking=no"
      with_items:
        - "{{ ec2.instances }}"
      no_log: true     
             
            
            
        
- name: "Updating SshKey Meterial"
  hosts: aws
  become: true
  gather_facts: false
  vars_files:
    - key.vars
  vars:
    old_key: "mumbai-production"
    tmp_key: "keypair-tmp"
  tasks:
    
    - name: "Creating New SSH-Kay Meterial"
      delegate_to: localhost
      run_once: True
      openssh_keypair:
        path: "{{ tmp_key }}"
        type: rsa
        size: 4096
        state: present
        
    - name: "Adding New SshKey Meterial"
      authorized_key:
       user: ec2-user
       state: present
       key: "{{ lookup('file', '{{ tmp_key }}.pub')  }}"
        
    - name: "Creating Ssh Connection Command"
      set_fact:
        ssh_connection: "ssh -o StrictHostKeyChecking=no -i {{ tmp_key }} {{ansible_ssh_user}}@{{ ansible_ssh_host }} 'uptime'" 

    - name: "Checking Connectivity To Ec2 Using Newly Added Key"
      ignore_errors: true
      delegate_to: localhost
      shell: "{{ ssh_connection }}" 
    
    - name: "Removing Old KeyMeterial"
      authorized_key:
       user: ec2-user
       state: present
       key: "{{ lookup('file', '{{ tmp_key }}.pub')  }}"
       exclusive: true
        
    - name: "Removing Old Ssh public From Aws Account "
      delegate_to: localhost
      run_once: True
      ec2_key:
        aws_access_key: "{{ access_key }}"
        aws_secret_key: "{{ secret_key }}"
        region: "{{ region }}"
        name: "{{ old_key }}"
        key_material: "{{ lookup('file', '{{ tmp_key }}.pub') }}"
        force: true
        state: present
            
    - name: "Renaming Local Pulbic Key"
      run_once: True
      delegate_to: localhost
      shell: "mv {{  tmp_key }}.pub  {{ old_key }}.pub"

    - name: "Renaming Local Private Key" 
      run_once: True
      delegate_to: localhost
      shell: "mv {{  tmp_key }}  {{ old_key }}.pem"